version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@1.0.82

workflows:
  terraform-tag:
    jobs:
      - reporting/terraform_checks:
          code_path: .
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v.*/
